services:
  - type: web
    name: my-php-app
    env: docker
    plan: free
    repo: https://github.com/TornikeKhutsishvili/Mico
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true